language: java
before_install:
  - sudo apt-get update -q
  - sudo apt-get install -q virtualbox --fix-missing
  - sudo wget -nv https://dl.bintray.com/mitchellh/vagrant/vagrant_1.7.2_x86_64.deb
  - sudo dpkg -i vagrant_1.7.2_x86_64.deb
  - sudo apt-get install git
  - git clone https://github.com/cockpit-project/cockpit.git && cd cockpit && sudo vagrant up
  - cd ..

after_success: cd cockpit && sudo vagrant destroy
after_failure: cd cockpit && sudo vagrant destroy


